### PR TITLE
Fix IPMI recon script so that it works with new style custom fields

### PR DESCRIPTION
**Pull request by Robert-Nelson**
Updates the IPMI recon script to pass parameters to the IPMI plugin using the
new style custom fields.

Add a field for specifying additonal options to ipmi-sensors.  This is required
for IPMI v2.0 devices and when using accounts with restricted privileges.

Fix some typos in the description for the recon script.

Fix a bug where the recon script never completed and kept processing the subnet
over and over due to an incorrect exit condition in the loop.

Change the packet count and timeout passed to ipmiping.  The previous values
required 9 seconds per address polled.  This meant it took almost 40 minutes
to scan one 256 address subnet.  The new values cut the time per address to
2 seconds.

### CODE REVIEW

**Comment by m-lopez-f** [comment]
Hello,
Error at line 50 in file ipmi-plugin.pl
"
Use of uninitialized value $extraopts in concatenation (.) or string at ./ipmi-plugin.pl line 50.
Can't exec "ipmi-sensors": No existe el fichero o el directorio at ./ipmi-plugin.pl line 50.
Use of uninitialized value $res in split at ./ipmi-plugin.pl line 52.
Use of uninitialized value $value in string eq at ./ipmi-plugin.pl line 55.
Use of uninitialized value $value in print at ./ipmi-plugin.pl line 62.
"
Please review code.

Regards

**Comment by nramon** [comment]
Hi Robert,

Great work. The plug-in works fine. It's true that there are some warnings, as Miguel pointed out, but most come from the original script!

The upgrade scripts have a couple of SQL errors. I'll merge your pull request and we'll fix them.

Thank you!

**Comment by Robert-Nelson** [comment]
What error are you seeing? I'm not seeing one here. 

I do however see perl errors if ipmi-sensor fails for some reason. I'll try and make it more robust. 

| From: "m-lopez-f" notifications@github.com
| To: "pandorafms/pandorafms" pandorafms@noreply.github.com
| Cc: "Robert Nelson" robertn@the-nelsons.org
| Sent: Thursday, May 28, 2015 12:23:34 AM
| Subject: Re: [pandorafms] Fix IPMI recon script so that it works with new style
| custom fields (#15)

| Hello,
| Error at line 50 in file ipmi-plugin.pl
| Please review code.

| Regards

| —
| Reply to this email directly or view it on GitHub .

**Comment by m-lopez-f** [comment]
In the end everything worked properly

**Pull request merged**
