### PR TITLE
[Enhancement] separate container for DB, server and console deployment (docker swarm ready)

### PR DESCRIPTION
**Pull request by marcelo-ochoa**
Main benefits:
- 3 separate containers
- optimized size for the images 578MB/609MB versus 1.30Gb oldest one
- update to MySQL 5.7, may be compatible with Maria DB
- separate functionality for cron jobs (align with Docker best practices), [swarm scheduler](https://store.docker.com/community/images/rayyanqcri/swarm-scheduler)
- configurable SMTP host/port, is better and recommendable in Docker postfix in a separate container
- external [config](https://docs.docker.com/engine/swarm/configs/#advanced-example-use-configs-with-a-nginx-service) to enable ssl support
- HA [load balancer](https://store.docker.com/community/images/dockercloud/haproxy) integration
- tested with SSL letsencrypt
I know that one Docker for all is a simple deployment option, but for production Docker Swarn scenery is better an stack like this:
```
# Environment variables MYSQL_DATABASE_PASSWORD=StrongPwd1
# Environment variables MYSQL_ROOT_PWD=StrongPwd2
# Required external configs pandora_console_ssl to enable ssl support
version: '3.3'

services:
  mysql:
    image: pandorafms-mysql:v7.0NG.722
    hostname: mysql
    volumes:
       - db_data:/var/lib/mysql
    restart: always
    environment:
      TZ: America/Argentina/Buenos_Aires
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}
      MYSQL_DATABASE: pandora
      MYSQL_USER: pandora
      MYSQL_PASSWORD: ${MYSQL_DATABASE_PASSWORD} 
      MYSQL_ROOT_HOST: "%"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    networks:
      net:
        aliases:
          - mysql
  server:
    image: pandorafms-server:v7.0NG.722
    hostname: pandorafms-server
    volumes:
       - web_plugin:/var/www/html/pandora_console/attachment/plugin
    depends_on:
      - mysql
    ports:
      - "41121:41121"
    restart: always
    environment:
      TZ: America/Argentina/Buenos_Aires
      MYSQL_PORT_3306_TCP_ADDR: mysql
      MYSQL_PORT_3306_TCP_PORT: 3306
      PANDORA_DB_HOST: mysql
      PANDORA_DB_USER: pandora
      PANDORA_DB_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      PANDORA_DB_NAME: pandora
      PANDORA_SMTP_HOST: smtphost.mydomain.tld
      PANDORA_SMTP_PORT: 25
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    networks:
      net:
        aliases:
          - pandorafms-server
  cron:
    image: pandorafms-server:v7.0NG.722
    command: /run_cron.sh
    environment:
      TZ: America/Argentina/Buenos_Aires
      MYSQL_PORT_3306_TCP_ADDR: mysql
      MYSQL_PORT_3306_TCP_PORT: 3306
      PANDORA_DB_HOST: mysql
      PANDORA_DB_USER: pandora
      PANDORA_DB_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      PANDORA_DB_NAME: pandora
      PANDORA_SMTP_HOST: smtphost.mydomain.tld
      PANDORA_SMTP_PORT: 25
    deploy:
      mode: replicated
      replicas: 0
      restart_policy:
        condition: none
    networks:
      net:
  web:
    image: pandorafms-console:v7.0NG.722
    hostname: mon.mydomain.tld
    volumes:
       - web_certs:/etc/ssl/certs:ro
       - web_plugin:/var/www/html/pandora_console/attachment/plugin
    depends_on:
      - mysql
    restart: always
    environment:
      TZ: America/Argentina/Buenos_Aires
      VIRTUAL_HOST: "https://mon.mydomain.tld"
      SERVICE_PORTS: "443"
      HEALTH_CHECK: "check ssl verify none"
      PANDORA_DB_HOST: mysql
      PANDORA_DB_USER: pandora
      PANDORA_DB_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      PANDORA_DB_NAME: pandora
    networks:
      net:
        aliases:
          - pandorafms-console
      rproxy:
        aliases:
          - monitoring
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    configs:
      - source: pandora_console_ssl
        target: /etc/httpd/conf.d/ssl.conf
        uid: '0'
        gid: '0'
        mode: 0644
volumes:
    db_data:
      driver: local
      driver_opts:
        type: nfs
        o: addr=NFS_server_or_NAS,rw,intr,hard,timeo=600,wsize=32768,rsize=32768,vers=3,tcp
        device: ":/docker/stacks/mon/db"
    web_certs:
      driver: local
      driver_opts:
        type: nfs
        o: addr=NFS_server_or_NAS,rw,intr,hard,timeo=600,wsize=32768,rsize=32768,vers=3,tcp
        device: ":/docker/stacks/letsencrypt/certs"
    web_plugin:
      driver: local
      driver_opts:
        type: nfs
        o: addr=NFS_server_or_NAS,rw,intr,hard,timeo=600,wsize=32768,rsize=32768,vers=3,tcp
        device: ":/docker/stacks/mon/plugin"
networks:
    net:
    rproxy:
        external:
            name: reverse_proxy
configs:
    pandora_console_ssl:
        external: true
```
In a separate stacks there is a Load Balancer using [HAProxy](https://store.docker.com/community/images/dockercloud/haproxy) which expose http/https access, [Swarm scheduler](https://store.docker.com/community/images/rayyanqcri/swarm-scheduler) for running Pandora Jobs and a [LetsEncrypt](https://store.docker.com/community/images/linuxserver/letsencrypt) stack for registering and renewing certificates.
Best regards, Marcelo.

### CODE REVIEW

**Comment by nramon** [comment]
Hola, Marcelo. Thanks a lot for your contributions. I'll check the PR right now!

**Comment by marcelo-ochoa** [comment]
Ramon:
   Sorry for the delay, I missed this minor conflicts, I resolved them a minutes ago.
  Best regards, Marcelo.

**Comment by marcelo-ochoa** [comment]
I committed some changes with these functionalities:

- Multi-stage build for faster image creation
- Partial git pull, reduce image size by 100Mb in Pandora console
Also removing repos that are not necessary for building Docker images
Best regards, Marcelo.

**Comment by marcelo-ochoa** [comment]
In order to work with latest release Dockerfile at pandora_server folder requires additional repo (RPMForge), now Geo-IP is required to install pandora server

**Comment by marcelo-ochoa** [comment]
Latest file changed fix:
   - disk_free bug when directory/filesystem have more than 1.7TB free
   - missing icon in pandora mobile UI
   - updated Docker file in pandora_console for using PHP 7.2 (avoid error 500 with apache server)

**Comment by netzulo** [comment]
I wanted to start my plugin development, but wanted to use docker for development process, community need @marcelo-ochoa changes please :) ( *or at least , i need it* ) 

*waiting for merge this...*

**Comment by marcelo-ochoa** [comment]
I just committed an hour ago an optimization with .dockignore file, some packages not included in Docker file for swarm deployment and a waiting functionality in pandora_server container to wait MySQL ready.
Marcelo.
PD: Here a sample docker-compose.yml file to get fresh start of pandora stack
```
# Environment variables export MYSQL_DATABASE_PASSWORD=pandora_password_here
# Environment variables export MYSQL_ROOT_PWD=root_password_here
# Required external configs pandora_console_ssl to enable ssl support
version: '3.3'

services:
  mysql:
    image: pandora/pandorafms-mysql:7.0NG.729-181205.7886
    hostname: mysql
    environment:
      TZ: America/Argentina/Buenos_Aires
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}
      MYSQL_DATABASE: pandora
      MYSQL_USER: pandora
      MYSQL_PASSWORD: ${MYSQL_DATABASE_PASSWORD} 
      MYSQL_ROOT_HOST: "%"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        window: 120s
    networks:
      net:
        aliases:
          - mysql
  server:
    image: pandora/pandorafms-server:7.0NG.729-181205.7886
    hostname: pandorafms-server
    depends_on:
      - mysql
    ports:
      - "41121:41121"
    environment:
      TZ: America/Argentina/Buenos_Aires
      MYSQL_PORT_3306_TCP_ADDR: mysql
      MYSQL_PORT_3306_TCP_PORT: 3306
      PANDORA_DB_HOST: mysql
      PANDORA_DB_USER: pandora
      PANDORA_DB_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      PANDORA_DB_NAME: pandora
      PANDORA_SMTP_HOST: mail.exa.unicen.edu.ar
      PANDORA_SMTP_PORT: 25
      PANDORA_SMTP_FROM: pandora@exa.unicen.edu.ar
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        window: 120s
    networks:
      net:
        aliases:
          - pandorafms-server
  web:
    image: pandora/pandorafms-console:7.0NG.729-181205.7886
    hostname: monitoring.exa.unicen.edu.ar
    depends_on:
      - mysql
    environment:
      TZ: America/Argentina/Buenos_Aires
      PANDORA_DB_HOST: mysql
      PANDORA_DB_USER: pandora
      PANDORA_DB_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      PANDORA_DB_NAME: pandora
    ports:
      - 8080:80
    networks:
      net:
        aliases:
          - pandorafms-console
      rproxy:
        aliases:
          - monitoring
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 3
        window: 120s
volumes:
    db_data:
networks:
    net:
    rproxy:

```

just start using command:
`docker stack deploy -c docker-compose.yml mon`

**Pull request closed without merging**
